// Code generated by cmd/gen-types; DO NOT EDIT.
package types

import (
	"database/sql/driver"
	"errors"

	"github.com/google/uuid"
)

type Types interface {
	ChatID | MessageID
}

func Parse[T Types](s string) (T, error) {
	u, err := uuid.Parse(s)
	return T(u), err
}

func MustParse[T Types](s string) T {
	return T(uuid.MustParse(s))
}

type ChatID uuid.UUID

var ChatIDNil = ChatID(uuid.Nil)

func NewChatID() ChatID {
	return ChatID(uuid.New())
}

func (r ChatID) String() string {
	return uuid.UUID(r).String()
}

func (r ChatID) Value() (driver.Value, error) {
	return r.String(), nil
}

func (r *ChatID) Scan(src any) error {
	return (*uuid.UUID)(r).Scan(src)
}

func (r ChatID) MarshalText() ([]byte, error) {
	return uuid.UUID(r).MarshalText()
}

func (r *ChatID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(r).UnmarshalText(data)
}

func (r ChatID) Validate() error {
	if r.IsZero() {
		return errors.New("zero ChatID")
	}
	return nil
}

func (r ChatID) Matches(x any) bool {
	v, ok := x.(ChatID)
	if !ok {
		return false
	}
	return r == v
}

func (r ChatID) IsZero() bool {
	return r == ChatIDNil
}

type MessageID uuid.UUID

var MessageIDNil = MessageID(uuid.Nil)

func NewMessageID() MessageID {
	return MessageID(uuid.New())
}

func (r MessageID) String() string {
	return uuid.UUID(r).String()
}

func (r MessageID) Value() (driver.Value, error) {
	return r.String(), nil
}

func (r *MessageID) Scan(src any) error {
	return (*uuid.UUID)(r).Scan(src)
}

func (r MessageID) MarshalText() ([]byte, error) {
	return uuid.UUID(r).MarshalText()
}

func (r *MessageID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(r).UnmarshalText(data)
}

func (r MessageID) Validate() error {
	if r.IsZero() {
		return errors.New("zero MessageID")
	}
	return nil
}

func (r MessageID) Matches(x any) bool {
	v, ok := x.(MessageID)
	if !ok {
		return false
	}
	return r == v
}

func (r MessageID) IsZero() bool {
	return r == MessageIDNil
}
