// Code generated by options-gen. DO NOT EDIT.
package managerhandler

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	eventReader EventReader,
	typingMessage TypingMessageUseCase,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.eventReader = eventReader
	o.typingMessage = typingMessage

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("eventReader", _validate_Options_eventReader(o)))
	errs.Add(errors461e464ebed9.NewValidationError("typingMessage", _validate_Options_typingMessage(o)))
	return errs.AsError()
}

func _validate_Options_eventReader(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventReader, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventReader` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_typingMessage(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.typingMessage, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `typingMessage` did not pass the test: %w", err)
	}
	return nil
}
