# https://taskfile.dev
version: '3'

silent: true

vars:
  GO_MODULE: github.com/lapitskyss/chat-service
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./internal/store/*" -not -path "*.gen.go" | tr "\n" " "

  GOLANGCI_LINT_VERSION: v1.54.2
  GOLANGCI_LINT_CACHE:
    sh: echo "$HOME/Library/Caches/GolangciLint"

  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.10.1
    mvdan.cc/gofumpt@v0.4.0
    github.com/kazhuravlev/options-gen/cmd/options-gen@v0.30.0
    entgo.io/ent/cmd/ent@v0.12.4
    github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.15.0
    go.uber.org/mock/mockgen@v0.3.0
    github.com/onsi/ginkgo/v2/ginkgo@v2.13.0

  TYPES: |
    ChatID
    ProblemID
    MessageID
    UserID
    RequestID

  DOCKER_COMPOSE_PATHS: |
    ./deploy/local/docker-compose.yml
    ./deploy/local/docker-compose.sentry.yml
    ./deploy/local/docker-compose.swagger-ui.yml

  DOCKER_COMPOSE_CMD: docker compose {{range .DOCKER_COMPOSE_PATHS | splitArgs }} -f {{.}} {{end}}

  ENT_SCHEMA: ./internal/store/schema
  ENT_TEMPLATES: ./internal/store/templates/database.tmpl
  ENT_FEATURES: sql/upsert

  CLIENT_V1_SRC: ./api/client.v1.swagger.yml
  CLIENT_V1_DST: ./internal/server-client/v1/server.gen.go
  CLIENT_V1_PKG: clientv1

  E2E_CLIENT_V1_DST: ./tests/e2e/api/client/v1/client.gen.go
  E2E_CLIENT_V1_PKG: apiclientv1

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    - echo "- Format"
    - gofumpt -l -w {{.GO_FILES}}
    - gci write -s standard -s default -s "prefix({{.GO_MODULE}})" {{.GO_FILES}}

  lint:
    cmds:
      - echo "- Lint"
      - mkdir -p {{.GOLANGCI_LINT_CACHE}}
      - task: lint:cmd
        vars: { CLI_ARGS: "run -v --fix --timeout=5m ./..." }

  lint:cmd:
    cmds:
      - |
        docker run --rm \
          -v "$(pwd):/app" -w /app \
          -v "{{.GOLANGCI_LINT_CACHE}}:/root/.cache" \
          golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} \
          golangci-lint {{.CLI_ARGS}}

  tests:
    cmds:
      - echo "- Tests"
      - go test -race ./...

  tests:integration:
    env:
      TEST_PSQL_USER: chat-service
      TEST_PSQL_PASSWORD: chat-service
      TEST_PSQL_DEBUG: true
      TEST_LOG_LEVEL: info
      TEST_KEYCLOAK_REALM: Bank
      TEST_KEYCLOAK_CLIENT_ID: integration-testing
      TEST_KEYCLOAK_CLIENT_SECRET: bAsBxAavMvxX4SeFx0g0yBarS8KPxYm7
      TEST_KEYCLOAK_TEST_USER: integration-testing
      TEST_KEYCLOAK_TEST_PASSWORD: integration-testing
    cmds:
      - echo "- Integration tests"
      - go test -tags integration -count 1 -race ./...

  tests:e2e:
    env:
      E2E_CLIENT_V1_API_ENDPOINT: http://localhost:8080/v1
      E2E_KEYCLOAK_BASE_PATH: http://localhost:3010
      E2E_KEYCLOAK_REALM: Bank
      E2E_KEYCLOAK_CLIENT_ID: e2e-testing
      E2E_KEYCLOAK_CLIENT_SECRET: qj2cDBSGdDgQFSqFcYV0tSUAXml1dQcS
      E2E_KEYCLOAK_CLIENT_DEBUG: false
      E2E_KEYCLOAK_CLIENTS: e2e_client_0,e2e_client_1
    cmds:
      - echo "- End-to-end tests..."
      # NOTE: It's important to run tests serial (without `-p` flag) – for correct `clientsPool` sharing.
      - "ginkgo --fail-fast --timeout=1m --tags e2e {{.CLI_ARGS}} ./tests/e2e"

  build:
    cmds:
      - echo "- Build"
      - go build ./cmd/chat-service
      - rm chat-service

  generate:
    - echo "Run go generate..."
    - go generate ./...
    - task: gen:types
    - task: ent:gen
    - task: gen:api
    - task: gen:e2e

  dev-tools:install:
    cmds:
      - echo "- Install dev tools"
      - for: { var: DEV_TOOLS }
        cmd: go install {{.ITEM}}

  deps:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} up -d"

  deps:cmd:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.CLI_ARGS}}"

  deps:status:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} ps"

  deps:logs:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} logs"

  deps:stop:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} stop"

  deps:reset-psql:
    cmds:
      - task: deps:reset
        vars:
          SERVICE: postgres

  deps:reset:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} rm -fsv {{.SERVICE}}"
      - "{{.DOCKER_COMPOSE_CMD}} up -d {{.SERVICE}}"

  ent:new:
    cmds:
      - ent new --target {{.ENT_SCHEMA}} {{.CLI_ARGS}}
      - task: tidy

  ent:gen:
    cmds:
      - ent generate {{.ENT_SCHEMA}} --template {{.ENT_TEMPLATES}} --feature {{.ENT_FEATURES}}
      - task: tidy

  kc:export:
    cmds:
      - echo "Dump Keycloak Bank realm..."
      - "{{.DOCKER_COMPOSE_CMD}} exec keycloak /opt/keycloak/bin/kc.sh export --file /tmp/realm.json --realm Bank"
      - echo "Exported in ./deploy/local/bank-realm.json"
      - "{{.DOCKER_COMPOSE_CMD}} cp keycloak:/tmp/realm.json ./deploy/local/bank-realm.json"

  gen:types:
    cmds:
      - echo "Generate types..."
      - go run ./cmd/gen-types types {{.TYPES | splitArgs | join ","}} ./internal/types/types.gen.go

  gen:api:
    cmds:
      - echo "Generate client server..."
      - oapi-codegen --old-config-style -generate types,server,spec -package {{.CLIENT_V1_PKG}} {{.CLIENT_V1_SRC}} > {{.CLIENT_V1_DST}}
      - task: tidy

  gen:e2e:
    cmds:
      - echo "[E2E] Generate client API..."
      - oapi-codegen --old-config-style -generate types,client -package {{.E2E_CLIENT_V1_PKG}} {{.CLIENT_V1_SRC}} > {{.E2E_CLIENT_V1_DST}}
