[global]
env = "dev"

[log]
level = "info"

[servers]
[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
[servers.debug]
addr = ":8079"

[sentry]
dsn = ""
